### ISSUE TITLE
Minor issue: Playbook vs Class

### ISSUE THREAD

**Issue by drewg13** [justinross/foundry-bitd-alternate-sheets#1]
The instruction in Edit mode states:
`Drop a Playbook Item on the sheet to switch Playbooks`

Using `Playbook` is correct within Blades terminology, but the Blades system keeps the 'Playbooks' in the `Classes` compendium and refers to 'Playbook Items' as Items with type `class`, which makes that a somewhat confusing directive.  It's really a problem with the base Blades system being incorrect and, if you were making your own forked system, it would make more sense to correct that, but since you're making a module dependent on the base Blades system, it might make more sense to follow that terminology instead.

**Comment by justinross** [comment]
Yeah, this has been something I've wrestled with here and there. Even naming things internally where I'm the only one looking at them. :)

You're right though, of course. It's confusing. I wonder how entrenched the "Class" compendium name is in the base system. Megastruktur has been fairly responsive to PRs... Maybe later.
