### ISSUE TITLE
Missing translation strings

### ISSUE THREAD

**Issue by drewg13** [justinross/foundry-bitd-alternate-sheets#2]
These lines of code (162-163) in `blades-alternate-actor-sheet.js`:
```js
title: game.i18n.localize("BITD.AddExisting" + Utils.capitalizeFirstLetter(item_type)),
content:  `<h3>${game.i18n.localize("BITD.SelectToAdd" + Utils.capitalizeFirstLetter(item_type))}</h3>
```
result in this at the top of the Dialog:
![image](https://user-images.githubusercontent.com/1455026/178993073-d26f15dd-6f24-430c-81a9-0c5bafbfb59a.png)

Also, line 182, I believe `Cancel` is hardcoded in the base Blades system, so this string is not available either:
```js
label: game.i18n.localize("BITD.Cancel"),
```

**Comment by drewg13** [comment]
Also, on a new Actor with no Playbook yet:
![image](https://user-images.githubusercontent.com/1455026/178999819-a287c04a-d164-40ea-94a6-8f247772d3c8.png)

**Comment by justinross** [comment]
Thanks! The BITD.Acquaintances one is trickier, since that's getting pulled directly from Class items in the system compendium. I've submitted a PR for adding the string, though (I just missed it when I created the different labels originally)
