### ISSUE TITLE
"Missing" Vampire ability in AddExistingAbility Dialog

### ISSUE THREAD

**Issue by drewg13** [justinross/foundry-bitd-alternate-sheets#3]
![image](https://user-images.githubusercontent.com/1455026/178995773-26b1b5ed-3f2e-4778-adf6-b5d776bd77a4.png)

This is caused by the use of quotes in the Arcane Sight description, which breaks your HTML for that item.  It feels like the choices to fix this are both ugly.  Either submit a PR to base Blades to change it from `"Hear"` to `'Hear'` and wait for megastruktur to eventually approve and release or build some sort of sanitization function.  Perhaps you can think of something more elegant.

**Comment by justinross** [comment]
I’ve actually made a few small PRs to the main system as part of getting all this running. Mega has been fairly quick about getting them in. I’ll probably go that route and sanitize the string for the sake of future proofing.

**Comment by drewg13** [comment]
Yeah, I recall this specific Arcane Sight issue cropping up with your previous replacement system too, so I immediately knew what it was.
