### ISSUE TITLE
Clicking Cancel when adding an existing item crashes Foundry

### ISSUE THREAD

**Issue by LordGinger** [justinross/foundry-bitd-alternate-sheets#35]
Steps to reproduce:
1. Go into a character sheet
2. Click the + next to Items
3. Click "Add existing item"
4. Click "Cancel"

Foundry will then crash entirely.

**Comment by justinross** [comment]
Yikes.

Foundry crashes as in, the server needs to be restarted? Or as in a page refresh is needed?

I’ll look into it.

Justin

**Comment by LordGinger** [comment]
The app closes with no error message. The debug logs all say this:
`{"level":"info","message":"Shutting down Foundry Virtual Tabletop server","timestamp":"2022-12-11 13:19:45"}`

I have to mention I'm using the desktop app on Windows, not joining the session from the browser. On the browser, it works fine. It might have something to do with the call to `close()`, in the function which creates the menu, being interpreted differently on the app; perhaps it is a scope binding issue.

**Comment by justinross** [comment]
Haha wow. Yeah I think that might be right. I’ll see what I can do to fix it.

Thanks for the info!

Justin

**Comment by justinross** [comment]
Latest release ... might (?) fix this.

**Comment by LordGinger** [comment]
It doesn't close Foundry now, but it does close the entire character sheet. Not just the Add Item window.

**Comment by LordGinger** [comment]
I fixed it locally by replacing
`callback: () => {this.close();}`
with
`callback: () => {}`

Per the docs, the default action for a button is to close the dialogue, so if you don't put anything between the brackets it only calls the dialog's close() method.

**Comment by justinross** [comment]
Ah cool. Thanks! I'll update.
