### ISSUE TITLE
Weird interaction between TinyMCE and Markdown

### ISSUE THREAD

**Issue by drewg13** [justinross/foundry-bitd-alternate-sheets#4]
![image](https://user-images.githubusercontent.com/1455026/178997330-4fd420ae-d08b-4185-ac34-2b6d3ce90dc2.png)

TinyMCE adds `<p>` tags, perhaps you could use your md helper to strip them out?

**Comment by justinross** [comment]
Is that a custom ability? I do need to sanitize those strings down to just text. I think I actually had in my old system version.

**Comment by drewg13** [comment]
One interesting thing to note is that V10 is adding Markdown support as well as changing out TinyMCE for ProseMirror for Journals, but they'll likely be available for use on sheets as well.

**Comment by justinross** [comment]
Interesting. That'll be a nice addition. Prosemirror will probably still cause the same issue. Basically I just need to strip out HTML tags before rendering the text. Ezpz.

**Comment by drewg13** [comment]
Playing with the new ProseMirror and Markdown type sheets right now.  They both do add the same `<p>` tags, but the ProseMirror simultaneous collaborative editing is really slick.
