### ISSUE TITLE
Auto Populate Acquaintances For Homebrew Classes

### ISSUE THREAD

**Issue by darkoutcast** [justinross/foundry-bitd-alternate-sheets#41]
Testing homebrew playbooks - class specific Actors for Homebrew playbooks don't pull from local Actor list. They do pull successfully if added to core NPCs compendium.

All Items appear to successfully populate, and drag from Actor tab is confirmed as working.

**Comment by justinross** [comment]
Yeah, I have some thoughts on reworking how playbooks are handled, but some of it would be moving outside the boundaries of a module and into a partial rewrite of the system (which isn’t off the table, but is a lot more involved).

I’ll see what I can do about this in the meantime, though.

**Comment by justinross** [comment]
I just realized ... how are you making homebrew playbooks? The playbook sheet doesn't show like, ANYTHING to edit. It's basically description, name, exp clues, and effects.

Tell me your secrets!

**Comment by justinross** [comment]
Oh disregard. I guess that's about all the data that's actually being stored. I forgot that the NPC/playbook association was happening on the NPC side, rather than the Playbook side. 

This should be fixed in the latest release.

**Comment by justinross** [comment]
Oh, and be sure to allow pulling from world sources in the module settings:

![image](https://user-images.githubusercontent.com/1120106/215589544-cc7fd301-4c37-4ea9-be81-0ec29dcfa5df.png)

**Comment by darkoutcast** [comment]
The way I’m making custom Playbooks is through Active Effects. I made a Sleuth playbook item, then made a Sleuth effect inside it that has overrides for acquaintance labels and experience. 


You can also use the effects to make Ghost and Hull playbooks have correct labels/arrays for Drain/Gloom/Wear but even that’s a small fix because to make it really work for a proper release, you’d really have to do pull requests for localization and core playbook edits to the main system. I can get away with small fixes locally because I’m just kludging together an English fix, which is as easy as an effect that overrides trauma options.
