### ISSUE TITLE
Issues with exp tracker on v1.0.2 sheet

### ISSUE THREAD

**Issue by kraDsec** [justinross/foundry-bitd-alternate-sheets#70]
Heyo, my table just started using your sheet for blades in the dark, and all the exp ticks are not working for any of us; on click of a pip it doesn't change anything on the sheet

**Comment by justinross** [comment]
Thanks for the report!

Is this just in the skills xp area (insight/prowess/resolve) or in the playbook xp as well?

Also, are you using your sheets in popout windows?

**Comment by kraDsec** [comment]
Both skills and playbook and in both popped out and mounted

**Comment by justinross** [comment]
Fixed in 1.0.3 (though, popouts have issues still I think)
