### ISSUE TITLE
Module isn't visible in the modules list when i search for it

### ISSUE THREAD

**Issue by FatatFza** [justinross/foundry-bitd-alternate-sheets#84]
Hi! Im trying to find your module but when i search for it in the list, it doesn't appear at all. When i use the manifested URL to install it manually it says "This module requires a newer version of foundry: 12 or newer" , Im currently using V11 :/ any help please? i really love the sheet and want to play blades in the dark using it as it has a much better structure and layout than the system provides on Foundry.

**Comment by justinross** [comment]
That’s likely to be my fault with the updates/manifest stuff. I’ll look into it more in the morning, but in the meantime, what happens if you use the direct link to the v 1.0.4 manifest? https://github.com/justinross/foundry-bitd-alternate-sheets/releases/download/1.0.4/module.json

**Comment by justinross** [comment]
Apparently I never set it up for v11. It should be in there now though. Maybe?
