### ISSUE TITLE
[Bug] Ticking an item's checkbox ticks all checkboxes

### ISSUE THREAD

**Issue by daalta** [justinross/foundry-bitd-alternate-sheets#95]
Thanks for creating this module! Unfortunately, I can't use it because multi-checkbox items can't be ticked individually.

I'm running version 1.0.13.
Foundry version 12 Stable, build 329.

![Foundry_Virtual_Tabletop_u0TVxxoEMT](https://github.com/user-attachments/assets/3f55a6a2-7c41-4d81-be4a-6a7ae0848243)

I think I'm the first user to report this bug, so maybe it's related to one of my other modules?
- Chat images
- Chat portrait
- Dice So Nice!
- Safety Tools
- Show Art
- Simple Calendar
- Simple Weather
- socketlib

**Comment by daalta** [comment]
Ah, never mind - I misunderstood how weight works in blades.

Thanks again for creating this sheet!

**Comment by justinross** [comment]
Haha, no problem. Glad you like the sheets! 😁
